name: IroCO2 feature template
description: Describe a new feature
type: Feature
projects: "IroCO2 Kanban board"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to our project!
        Thanks for taking the time to fill out this form.
  - type: textarea
    attributes:
      label: Objective
      description: The objective of the item (reflects the value of the item/feature to be implemented)
  - type: textarea
    attributes:
      label: Description
      description: Describe the new feature
